### ISSUE TITLE
İçeriklere yorum bildirimlerinin kapatılabilmesi seçeneğinin eklenmesi

### ISSUE THREAD

**Issue by ssduzel** [cilerler/testidea#1]
Kullanıcıların, istediği içerik için yorum bildirimlerinin kapatılmasını sağlayan bir seçeneğin oluşturulması

**Comment by cilerler** [comment]
@AydinKaya80 bu konuda ne dusunuyorsun?

**Comment by AydinKaya80** [comment]
Ayarlar sayfasina bildirimler diye bir kategori koyup oradan acilip kapatabilsin.

**Comment by berkbaski** [comment]
@AydinKaya80 ben bu konuda yeterli bilgiye sahip degilim. egitime ihtiyacim var.
